include:
  - ./docker-compose.mongo.yml
  - ./packages/api/docker-compose.yml
  - ./packages/proxy/docker-compose.yml
services:
  ui:
    image: nginx
    restart: unless-stopped
    container_name: ui
    volumes:
      - ./packages/ui/dist:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8088:80
    networks:
      - freeboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  freeboard:
    external: true
