services:
  mongo:
    image: ${FREEBOARD_MONGO_IMAGE:-mongo}
    restart: unless-stopped
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ${FREEBOARD_MONGO_DB_PATH:-./db}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: freeboard
      MONGO_INITDB_ROOT_PASSWORD: unsecure
      MONGO_INITDB_DATABASE: freeboard
