include:
  - ./docker-compose.dev.yml
services:
  frontend:
    restart: unless-stopped
    build:
      context: packages/ui
      dockerfile: Dockerfile
    environment:
      - FREEBOARD_BACKEND_URL=http://backend:4001
      - FREEBOARD_PROXY_URL=http://proxy:4001
      - FREEBOARD_NODE_MODULES=./node_modules
    ports:
      - 4173:4173
    depends_on:
      - backend
      - proxy
  backend:
    restart: unless-stopped
    build:
      context: packages/api
      dockerfile: Dockerfile
    environment:
      - mongoURI=mongodb://root:unsecure@mongo:27017
      - secretOrKey=DEHEiRMt32flRLcntMyH3mmeflLiAVuv
    ports:
      - 4001:4001
    depends_on:
      - mongo
  proxy:
    restart: unless-stopped
    build:
      context: packages/proxy
      dockerfile: Dockerfile
    ports:
      - 8001:8001
