include:
  - ./docker-compose.mongo.yml
  - ./packages/api/docker-compose.yml
  - ./packages/proxy/docker-compose.yml
services:
  ui:
    restart: unless-stopped
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FREEBOARD_NODE_MODULES=./node_modules
    ports:
      - 8087:80
