services:
  api:
    restart: unless-stopped
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FREEBOARD_MONGO_URL=mongodb://root:unsecure@mongo:27017
    ports:
      - 4001:4001
    networks:
      - freeboard
