services:
  api:
    restart: unless-stopped
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - mongoURI=mongodb://root:unsecure@host.docker.internal:27017
    ports:
      - 4001:4001
    networks:
      - freeboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
