services:
  api:
    restart: unless-stopped
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FREEBOARD_MONGO_URL=${FREEBOARD_MONGO_URL:-mongodb://root:unsecure@localhost:27017}
    ports:
      - 4001:4001
    networks:
      - freeboard
