services:
  api:
    restart: unless-stopped
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - mongoURI=mongodb://root:unsecure@localhost:27017
      - secretOrKey=DEHEiRMt32flRLcntMyH3mmeflLiAVuv
    ports:
      - 4001:4001
